### ISSUE TITLE
Add samples using the payment transaction APIs

### ISSUE THREAD

**Issue by 0xunreal** [Origin-Byte/sui-unity-sdk#10]
Add a sample that demonstrates pay, transfer coins. Also update documentation.

**Comment by navedjuwale-creator** [comment]
Hi, I came across this issue while looking for payment transaction API examples. I'm interested in contributing and wondering if there's a specific reason this was closed as not planned. Would it still be valuable to add samples for pay and transfer coins? If so, I'd be happy to work on it and update the documentation. Let me know if there's any guidance. Thanks!
